// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;
using Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EvacuationPlanning.Migrations
{
    [DbContext(typeof(EvacuationPlanningDbContext))]
    [Migration("20251224155011_EvacuationZoneMigration")]
    partial class EvacuationZoneMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.EvacuationZone", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("NumberOfPeople")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_people");

                    b.Property<int>("UrgencyLevel")
                        .HasColumnType("integer")
                        .HasColumnName("urgency_level");

                    b.Property<string>("ZoneID")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zone_id");

                    b.HasKey("Id");

                    b.ToTable("evacuation_zone");
                });
#pragma warning restore 612, 618
        }
    }
}
