// <auto-generated />
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EvacuationPlanning.Migrations
{
    [DbContext(typeof(EvacuationPlanningDbContext))]
    [Migration("20251228162431_EvacuationStatusMigration")]
    partial class EvacuationStatusMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.EvacuationPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("ETA")
                        .HasColumnType("double precision")
                        .HasColumnName("eta");

                    b.Property<int>("NumberOfPeople")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_people");

                    b.Property<long>("VehicleID")
                        .HasColumnType("bigint")
                        .HasColumnName("vehicle_id");

                    b.Property<long>("ZoneID")
                        .HasColumnType("bigint")
                        .HasColumnName("zone_id");

                    b.HasKey("Id");

                    b.HasIndex("VehicleID");

                    b.HasIndex("ZoneID");

                    b.ToTable("evacuation_plan");
                });

            modelBuilder.Entity("Models.EvacuationStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("LastVehicleUsed")
                        .HasColumnType("bigint")
                        .HasColumnName("last_vehicle_used");

                    b.Property<int>("RemainingPeople")
                        .HasColumnType("integer")
                        .HasColumnName("remaining_people");

                    b.Property<int>("TotalEvacuated")
                        .HasColumnType("integer")
                        .HasColumnName("total_evacuated");

                    b.Property<long>("ZoneID")
                        .HasColumnType("bigint")
                        .HasColumnName("zone_id");

                    b.HasKey("Id");

                    b.HasIndex("LastVehicleUsed");

                    b.HasIndex("ZoneID");

                    b.ToTable("evacuation_status");
                });

            modelBuilder.Entity("Models.EvacuationZone", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<int>("NumberOfPeople")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_people");

                    b.Property<int>("UrgencyLevel")
                        .HasColumnType("integer")
                        .HasColumnName("urgency_level");

                    b.Property<string>("ZoneID")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zone_id");

                    b.HasKey("Id");

                    b.ToTable("evacuation_zone");
                });

            modelBuilder.Entity("Models.Log", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("RemainingPeople")
                        .HasColumnType("integer")
                        .HasColumnName("remaining_people");

                    b.Property<int>("TotalEvacuated")
                        .HasColumnType("integer")
                        .HasColumnName("total_evacuated");

                    b.Property<long>("VehicleID")
                        .HasColumnType("bigint")
                        .HasColumnName("vehicle_id");

                    b.Property<long>("ZoneID")
                        .HasColumnType("bigint")
                        .HasColumnName("zone_id");

                    b.HasKey("Id");

                    b.HasIndex("VehicleID");

                    b.HasIndex("ZoneID");

                    b.ToTable("log");
                });

            modelBuilder.Entity("Models.Vehicle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<int>("Speed")
                        .HasColumnType("integer")
                        .HasColumnName("speed");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("VehicleID")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.ToTable("vehicle");
                });

            modelBuilder.Entity("Models.EvacuationPlan", b =>
                {
                    b.HasOne("Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.EvacuationZone", "EvacuationZone")
                        .WithMany()
                        .HasForeignKey("ZoneID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvacuationZone");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Models.EvacuationStatus", b =>
                {
                    b.HasOne("Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("LastVehicleUsed")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.EvacuationZone", "EvacuationZone")
                        .WithMany()
                        .HasForeignKey("ZoneID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvacuationZone");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Models.Log", b =>
                {
                    b.HasOne("Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.EvacuationZone", "EvacuationZone")
                        .WithMany()
                        .HasForeignKey("ZoneID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvacuationZone");

                    b.Navigation("Vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
